adrienverge/openfortivpn

src/ipv4.c

Apparently, the default route is not automatically restored on all linux
distribution.
Uncomment appropriate code to set default route when restoring routes.
I'm on debian wheezy OS.

Restore default route

---

configure.ac
src/hdlc.c
src/http.c
src/http.h
src/tunnel.c

This time successfully tested with FortiOS 5 and some other unknown version which is considerably more buggy and picky.
Tested against a mockup too; here's the tool used:
https://git.gnome.org/browse/network-manager-fortisslvpn/tree/contrib
It would be cool if @jpoet and @k0k could verify if this works well for them and possibly use sslproxy.pl to capture the traffic that doesn't work (don't publish the dumps as they are; they could contain secrets!).
If it turns to work well it would be cool to have a tagged release the Linux distros could ship.

Some more fixes

---

LICENSE
LICENSE.OpenSSL
src/io.c
src/ssl.h
src/tunnel.c
src/tunnel.h

In order to be allowed to package openfortivpn in a distribution, the
license must be slightly modified. This patch adds an exception in it.
See this explanation from Lubomir Rintel:
There's a well known clash between the licenses (OpenSSL adds an
"additional restriction" which is specifically not allowed by GPL).
Therefore the license doesn't allow anyone to redistribute the
resulting binaries (since a e.g. a Linux distro shipping both is
technically a derived work of the package).

Fix GPL + OpenSSL license clash

---

Makefile.am
src/http.c
src/http.h
src/ipv4.c
src/ipv4.h
src/tunnel.c
src/xml.c
src/xml.h

Only supports FortiOS 5 with /remote/fortisslvpn_xml resource. For FortiOS we'd need to parse the /remote/fortisslvpn response it seems.
Adds some hooks for NetworkManager to manage the routes too.

Understand split VPN routes

---

doc/openfortivpn.1
src/config.h
src/main.c
src/tunnel.c

For consistency with other pppd-related options, and to preserve the
ability to add a plugin system to openfortivpn in the future, rename
the pppd plugin option to --pppd-plugin.

config: Rename --plugin to --pppd-plugin

---

src/config.h

COOKIE_SIZE was recently changed from 213 to 240 to support newer VPN versions.
It seems that it was still not enough for some versions. This patchs sets it to 300 bytes.
References:
* https://github.com/adrienverge/openfortivpn/issues/18#issuecomment-158406434
* https://github.com/adrienverge/openfortivpn/pull/23#issuecomment-161621177

Increase COOKIE_SIZE (again)

---

README.md
doc/openfortivpn.1
src/config.h
src/http.c
src/main.c

The official fortinet client accepts a connection string of the form:
https://<vpnhost>:<port>/<realm>
Most VPN setups do not use the realm, so it's empty. It's only used
to provide multiple VPNs with different configuration on the same gateway.
This commit adds a --realm option to specify an authentication realm
to authenticate to. It defaults to empty.

Add support for realm authentication

---

src/http.c

Previously, we assumed that the tokeninfo parameter must be present and
contain data if we are to perform two-factor authentication. Based on
GitHub issue #41, in some cases, the tokeninfo parameter will be present
but contain an empty string.
This commit removes the check for string length, as it was not needed.

Perform 2FA auth with zero-length tokeninfo

---

src/ipv4.c

In `ipv4_add_nameservers_to_resolv_conf()` the initial content was got,
then rewritten using:
fread(buffer, stat.st_size, 1, file)
fputs(buffer, file);
This assumes the buffer is terminated by `\0`, which is not necessarily
the case.
Fixes: #44

ipv4: Fix non null-terminated buffer write

---

src/http.c
src/ipv4.c

Some VPNs do not have "assigned-addr" set in the configuration XML
file, but still supply split route information. In this case, set
up routes using the interface instead of a gateway address.

split routes: Use interface if assigned-addr is missing in XML

---

src/http.c

Misconfiguration from my part triggered a code path which causes a crash. This is a fix for that.
The crash is caused by freeing of an uninitialized pointer, the fix simply initializes it.
This also shows up when running with clang scan-build for those that are interested!

http: auth_log_in: Initialize res to avoid crash on http_request() error

---

src/userinput.c

Note that getchar() returns an unsigned char cast to an int,
which we cast back to a char.
Fixes: #30

userinput: fix compiler warning

---

src/config.c
src/tunnel.c

Now we compare only the contents of the certificate hash (without the
trailing 0-byte) and when copying it we add a 0-byte, not the other way
round.

Fix off-by-one error in trusted-cert

---

src/hdlc.h

I'm in the process of porting this to OpenWRT -- The ssize_t type seems to be defined only when including unistd.h.

At least for openwrt this needs unistd.h

---

src/config.c
src/config.h
src/main.c
src/tunnel.c

Sometimes we don't want pppd to change /etc/resolv.conf
so we have an option to turn this off and a config-file
variable which by default is on.

Option: --pppd-no-peerdns cfg: pppd-use-peerdns

---

doc/openfortivpn.1
src/config.c
src/config.h
src/main.c
src/tunnel.c

It is still possible to re-enable SSLv3/compression through --insecure-ssl
or config file, or to specify a different cipher-list.
The insecure-ssl option covers both the option and cipher list as it is
more accessible, and if SSLv3 is allowed then weak ciphers probably aren't
too high on priority list...
If the server does not accept either TLS protocols or cipher the user will
get a message similar to this one:
ERROR:  SSL_connect: error:14077410:SSL routines:SSL23_GET_SERVER_HELLO:sslv3 alert handshake failure
You might want to try --insecure-ssl or specify a different --cipher-list
Closes #69.

tunnel: disable insecure openssl default protocols/ciphers

---

configure.ac
doc/openfortivpn.1.in
src/main.c

as already mentioned in issue https://github.com/adrienverge/openfortivpn/issues/75 when running openfortivpn without any arguments it always searched the config file at the hard coded location /etc/openfortivpn/config
This pull request inserts the values for prefix and sysconfdir from configure time into the code via preprocessor defines. 
Previously, I have merged back the update to the man page etc. into my master branch, hoping that this doesn't disturb merging in the new changes. If it is better to delete this branch and fork again for the next pull-request, just drop me a message.

honor --sysconfdir during runtime

---

src/log.c

switching the foreground color to white might not be a good idea on a bright background. Switching to bold looks nearly the same on a dark background and the characters stay visible on bright background as a fix for issue #85

fix for #85 diagnostic message colors invisible

---

src/tunnel.c

When ppp connections are existed before connect with openfortivpn, openfortivpn use only 'ppp0'.
So, after connect vpn with openfortivpn that situation, routing table get tangled.
There is also same situation when connecting one more vpn with only openfortivpn.
So, I changed checking new connection logic.

fix detecting new connection bug when ppp connections are existed.

---

src/ipv4.c

This is a larger rework of the routing code, here a summary of the changes (for a detailed discussion see in issue #94 ):
- in ipv4_set_split_routes: add a host route to the gateway (basically copy&paste code from ipv4_set_default_routes)
- also in  ipv4_set_split_routes: merge in the two fixes for #25, namely add the gateway flag to these routes and corrected the test of the gateway ip (I have merged in pull request #88 here, for details see there). @adrienverge: if you want to merge this as a separate pull, please let me know and I can undo the changes in my branch.
- in ipv4_set_default_routes: change the route flag to host instead of gateway for the  route to the Fortigate. This is important when the existing default route is over a ppp device.
- in ipv4_restore_routes: remove the …

set up routes correctly (pull request for #94)

---

README.md

'KernelRepo/Documentation/CodingStyle' has moved to 'KernelRepo/Documentation/process/coding-style.rst'
http://git.kernel.org/cgit/linux/kernel/git/torvalds/linux.git/tree/Documentation/CodingStyle?id=refs/heads/master

README.md: Change CodingStyle Link

---

src/tunnel.c

Load the OS trusted certificate stores using
the default paths that are compiled in to
the OS-shipped OpenSSL libraries.

Load OS trusted certificate stores

---

src/ipv4.h

My company use more than 32 route tables.

Increase 'MAX_SPLIT_ROUTES' (32 -> 64)

---

README.md

'brew' usage is changed.
When I ran 'brew install automake autoconf homebrew/versions/openssl101', brew showed this messages.
```
$ brew install automake autoconf homebrew/versions/openssl101
Updating Homebrew...
Error: No available formula with the name "homebrew/versions/openssl101" 
==> Searching for a previously deleted formula...
homebrew/versions/openssl101 was deleted from homebrew/versions in commit 4d7efbf:
openssl101: remove "unacceptable" old version (https://github.com/Homebrew/homebrew-versions/issues/1528)
To show the formula before removal run:
git -C "$(brew --repo homebrew/versions)" show 4d7efbf^:openssl101.rb
If you still use this formula consider creating your own tap:
http://docs.brew.sh/How-to-Create-and-Maintain-a-Tap.html
```
I found that …

README.md: modify 'macOS' part in 'Installing' Section

---

src/ipv4.c

On MacOSX /proc file system is not available by default. As a fallback in ipv4_get_route parse the output  of netstat instead. Also thanks to @Mabin-J for testing and helping to improve this commit

MacOSX version of ipv4_get_route

---

README.md
doc/openfortivpn.1.in
src/config.c
src/config.h
src/main.c

(-o was not recognized before), and free all pointers in destroy_vpn_config

minor fixes to documentation, command line argument handling

---

README.md

Nothing but adding another install dependencies for another distro to the README.

Add openSUSE dependencies to README

---

src/io.c

When I run openfortivpn without elevate privileges in Linux,
it is finished normally but not in macOS.
It showed `INFO:   Cancelling threads...` and locked.
It didn't response when I push `Ctrl + C`
This is full message.
```
$ ./openfortivpn -c connect_info.config -v
DEBUG:  Loaded config file "connect_info.config".
VPN account password: 
DEBUG:  Config host = "123.123.123.123"
DEBUG:  Config realm = ""
DEBUG:  Config port = "443"
DEBUG:  Config username = "username"
DEBUG:  Config password = "********"
WARN:   This process was not spawned with root privileges, this will probably not work.
DEBUG:  Gateway certificate validation failed.
DEBUG:  Gateway certificate digest found in white list.
INFO:   Connected to gateway.
INFO:   Authenticated.
DEBUG:  Cookie: SVPNCOOKIE=[COOKIE]
INFO: …
```

fix lock status when fail to spawn pppd in macOS.

---

src/io.c

Not sure about this one:
- Why do we avoid calling _pthread_sigmask()_ on MacOS X to disable signal handling in future threads?
- Why are we using C's _signal()_ instead of POSIX _sigaction()_?
See for example:
- [What is the difference between sigaction and signal?](https://stackoverflow.com/questions/231912/what-is-the-difference-between-sigaction-and-signal#232711)
Fixes #78.

Handle SIGTERM as SIGINT and ignore SIGHUP

---

src/io.c

This commit is related with #132 and 158f4894ed5164991168a66bba874a9a268d4bbb .
It seems that `pthread_cancel` cannot effect to `dispatch_semaphore_wait`.
(`dispatch_semaphore_wait` is used for `sem_wait` for macOS, [io.c#L41](https://github.com/adrienverge/openfortivpn/blob/158f4894ed5164991168a66bba874a9a268d4bbb/src/io.c#L41))
It seems that `dispatch_semaphore_wait` not use real semaphore.
If `pthread_cancel cannot` effect to `dispatch_semaphore_wait`, 
`if_config` should be returned at `sem_wait(&sem_if_config);`([io.c#L509](https://github.com/adrienverge/openfortivpn/blob/158f4894ed5164991168a66bba874a9a268d4bbb/src/io.c#L509)) but it isn't...
`openfortivpn` is locked that line.
#132 is not best solution because when run `sem_post(&sem_if_config);`([io.c#L299](https://github.com/adrie …

fix core cause of openfortivpn is locked when spawning `ppp` is failed.

---

src/ipv4.c

Increasing MAX_SPLIT_ROUTES from 64 to 128 also increased the potential
number of digits in ipv4_config.split_routes from 2 to 3. Part of the
code expected the number of digits of ipv4_config.split_routes to be 2.
Increase to 3 to avoid buffer overrun and memory corruption.
Fixes #140.
At some point such well hidden dependencies will have to be removed for better maintainability. For now let's just fix this buffer overrun issue.

Fix buffer overrun

---

src/ipv4.c

* avoid double consecutive initialization of variable mask
* typo in log message
* very minor change in source code comment

Fix a few minor typos

---

.gitignore
.travis.yml
README.md
autogen.sh
configure.ac

Configure openssl

---

src/config.c

I'm a big fan of this handy tool, but after our VPNs got upgraded and auth realms were introduced I discovered that the 'realm' option can only be passed through the command line, not through the configfile.   
The proposed change enables that behavior by adding 'realm' to the list of keywords checked for in the configfile on launch.

Providing an option for setting the authentication realm in the configfile

---

doc/openfortivpn.1.in
src/config.c
src/config.h
src/ipv4.c
src/main.c

This merges the routing improvement proposed by @martinetd in #149 together with a command line option to select this type of behavior explicitly. The corresponding config file option is also added and the man page and help message are updated to reflect the new option

Add half-internet-routes as an option to influence how default routing is handled

---

README.md

...instead of --with-openssl option which has been removed again,
also mention that openfortivpn is available in Homebrew, now

update README.md and mention PKG_CONFIG_PATH

---

src/config.h
src/main.c

initialization took place in a macro, except for a few variables of the config. This patch cleans that up and moves all initialization into the macro. There were also a few grammar mistakes in the error messages that may printed out when wrong values were supplied for the command line options

clean up config initialization and error messages during parsing options

---

src/tunnel.c

The error handling of execvp in the forked child is bad.
Instead of returning into the original forked process, it should
exit immediately after execvp. This only happens if execvp fails
for some reason, which is probably a very rare situation.
But anyway it is better to be fixed.

Fix bug in pppd_run forking code

---

src/http.c
src/ipv4.c
src/log.c
src/main.c
src/tunnel.c

From [Linux kernel coding style](https://www.kernel.org/doc/html/latest/process/coding-style.html):
Linux kernel style for use of spaces depends (mostly) on function-versus-keyword usage. Use a space after (most) keywords. The notable exceptions are sizeof, typeof, alignof, and \_\_attribute\_\_, which look somewhat like functions (and are usually used with parentheses in Linux, although they are not required in the language, as in: `sizeof info` after `struct fileinfo info;` is declared).
So use a space after these keywords:
`if, switch, case, for, do, while`
but not with sizeof, typeof, alignof, or \_\_attribute\_\_. E.g.,
`s = sizeof(struct file);`

Consistently use Linux kernel coding style

---

src/io.c

This static analysis tool emits this single warning.
Once fixed, I could have Travis run _scan-build_ automatically.
Also the code was "prettyfied" for consistency between `pool_pop()` and `pool_push()`.

Fix warning from static analysis tool scan-build

---

src/config.h
src/http.c

Fixes #171.
* Increase cookie size to 4096, the maximum cookie size as per [RFC 2109](https://www.ietf.org/rfc/rfc2109.txt).
* Add some code to bail out should ever the cookie size be larger than that limit.

Cookie size

---

src/tunnel.c
src/tunnel.h

Borrowed from the Linux kernel (include/linux/kernel.h).
ARRAY_SIZE(x) returns the number of elements in an array.

Define and use the ARRAY_SIZE macro

---

src/tunnel.c

The obsolescent gethostbyaddr() is not part of POSIX any more.
The last POSIX version to support gethostbyaddr() is
The Open Group Base Specifications Issue 6, IEEE Std 1003.1, 2004 Edition:
The gethostbyname() function shall return an entry containing
addresses of address family AF_INET for the host with name name.
The current POSIX version, The Open Group Base Specifications Issue 7,
IEEE Std 1003.1-2008, 2016 Edition, reads:
The obsolescent h_errno external integer, and the obsolescent
gethostbyaddr() and gethostbyname() functions are removed,
along with the HOST_NOT_FOUND, NO_DATA, NO_RECOVERY, and TRY_AGAIN
macros.

gethostbyname -> getaddrinfo

---

src/config.h
src/hdlc.h
src/http.h
src/io.h
src/ipv4.h
src/log.h
src/ssl.h
src/tunnel.h
src/userinput.h
src/xml.h

Also add an _OPENFORTIVPN prefix to avoid collisions with external headers.

Fix missing or misnamed header guards

---

src/tunnel.c

We provide the full path to /usr/sbin/pppd. No need to search the PATH
with execvp(), execv() is enough.

execvp() -> execv()

---

src/tunnel.c

See for example [Why use _exit rather than exit in the child branch of a fork? ](http://www.unixguide.net/unix/programming/1.1.3.shtml) in the Unix programming FAQ.

Call _exit() instead of exit() after fork()

---

src/tunnel.c

Use log_error() instead of log_debug() in case of pppd failure.
In case of abnormal exit, print the termination signal.
Use shorter variable names for readability.

Better error handling of pppd exit status

---

src/tunnel.c

Disregard this error status code, at least until we get more
precise information from pppd, such as the pppd stderr stream.
See issue #184 and specifically [the last comment](https://github.com/adrienverge/openfortivpn/issues/184#issuecomment-338839895). Also reproducing this myself on Ubuntu 16.04.

Exit status code returned by normal pppd termination

---

src/tunnel.c

Use C99 struct initialization to ensure other struct members are properly
initialized to 0 and avoid this Valgrind message:
Syscall param ioctl(TCSET{S,SW,SF}) points to uninitialised byte(s)
at 0x5A03510: tcsetattr (tcsetattr.c:83)
by 0x54E85F0: openpty (openpty.c:121)
by 0x54E8683: forkpty (forkpty.c:31)
by 0x40BBE9: pppd_run (tunnel.c:116)
by 0x40BBE9: run_tunnel (tunnel.c:761)
by 0x403F7A: main (main.c:428)

Avoid Valgrind warning

---

src/io.c
src/ipv4.c
src/log.c

* Use strerror(errno) whenever possible.
Both malloc() and realloc() set errno when they fail under POSIX.
* Use either of "Not enough memory" or "malloc failed" but not both.

Standard error message for malloc()/realloc()

---

src/main.c

Was incorrectly using the variable name with underscores instead of
what we expect.

Fix usage string for half-internet-routes

---

configure.ac
src/tunnel.c

Hi,
When establishing a connection, the Common Name field in the target's certificate is explicitly checked, which results in an (overridable) failure when the hostname is not in the CN, but is in the Subject Alternative Name field (e.g. in multi-domain certs).
I've changed this to use openssl native X509_check_host instead--[the wiki](https://wiki.openssl.org/index.php/Hostname_validation) reports this is available in 1.0.2+/1.1+, and it adds an additional dependency on <openssl/x509v3.h>. Hopefully that's ok?

Use X509_check_host instead of explicit CN match.

---

src/tunnel.c

Previous rebase of 25643d6 did not work as expected. Sorry about that.

Explain why Coverity defect is a false positive

---

doc/openfortivpn.1.in
etc/ppp/ip-down.local.example
etc/ppp/ip-up.local.example
etc/ppp/peers/openfortivpn
src/config.c
src/config.h
src/ipv4.c
src/main.c
src/tunnel.c

On systems where pppd supports the "call" option --- eg. Debian derived
distros --- privileged options to pppd can be moved to a config file owned
by root, and any unprivileged user in group "dip" can invoke openfortivpn.
Static routes and DNS settings are managed by /etc/ppp/ip-up.local and
/etc/ppp/ip-down.local scripts, provided the following lines are added
to /etc/openfortivpn/config:
```
set-routes = 0
set-dns = 0
pppd-ipparam = openfortivpn
pppd-call = openfortivpn
```

Add --pppd-call option.

---

README.md

openfortivpn package is available in Debian testing - https://packages.debian.org/buster/openfortivpn

Add info about Debian (testing) package to readme

---

src/tunnel.c

Fixes #273.
The enumeration of pppd exit status codes was off by one
in the HTML man page this code was based on.

Print proper pppd status messages

---

src/http.c

Assume the second factor is the one-time password. The distinction
between a mechanism OTP is requested from how 2FA token is requested
doesn't provide much clue into what's the distinction. Assume they're
the same thing, not used together.
This allows the NetworkManager (that sets the otp key in config) to work
with 2FA setups.

If the OTP is specified in the configuration, use it for 2FA

---

src/tunnel.c
src/userinput.c
src/userinput.h

Also size_t is defined in both <stddef.h> (C) and <sys/types.h> (POSIX).
Use the second for consistency, and include before using size_t.

socket() requires <sys/socket.h>

---

configure.ac
src/log.c

Build with missing pthread_mutexattr_setrobust()

---

Makefile.am
configure.ac

Currently, X509_check_host function is always marked as missing, since
AC_CHECK_FUNCS is missing linker flags for libssl and libcrypto.
Culprit for this is the PKG_CHECK_MODULES call that does not add
libraries to the link arguments that configure uses to create function
tests, which in turn makes function check fail.
To remedy the situation, this commit replaces PKG_CHECK_MODULES with
two AC_CHECK_LIB calls (one for libcrypto and one for libssl) that
properly populate configure linker flags.

Rework OpenSSL library detection

---

Makefile.am
configure.ac

It breaks builds on macOS and other systems where OpenSSL headers and
libraries are not available in system directories.
We still need a proper solution for AC_CHECK_FUNCS to work properly.

Revert 79f52ef

---

.travis.yml
ci/install_astyle.sh
ci/install_openssl.sh

This pull request contains changes to Travis integration that will make future modifications a bit easier.
There are two things that this pull request achieves:
1. clean-up of existing CI stuff (astyle related dependencies) and
2. installation of fixed OpenSSL version that we would like to test building against.
This work will all us to rebase and apply changes in pull request #306 and resolve bug #304

Refactor CI

---

configure.ac

The OPENSSL_CFLAGS and OPENSSL_LIBS flags were taken into account in
Makefile.am, but not in configure.ac when testing for X509_check_host.
Fixes #304.

Use PKG_CHECK_MODULES compiler/linker flags

---

.travis.yml

This way these configure options do get tested at build time by Travis CI.

Restore configure options removed in ac5c083

---

.travis.yml

Not sure we can define multiple recipients.
Defining myself as the recipient for now as I'm currently working on Coverity warnings.

Temporarily change recipient of Coverity reports

---

doc/openfortivpn.1.in
src/main.c

Also in the example config file suggest this setting
which will hopefully be the default setting soon:
set-dns = 0

Documentation: we -> openfortivpn

---

doc/openfortivpn.1.in

* Fix formatitng issues.
* Consistency between manual page and --help.
* Break long lines in manual page source for consistency.

Minor manual page fixes

---

README.md
doc/openfortivpn.1.in
src/main.c

From now on _openfortivpn_ will not attempt to modify DNS settings and `/etc/resov.conf` by default. Instead leave it to _pppd_ to handle DNS (or not if `--pppd-no-peerdns`).
* Option `set-dns` is now disabled by default.
* Remove `--no-dns` which is now useless.
This is a first step towards entirely getting rid of `--set-dns` as suggested in #230 and #101.

Let pppd handle DNS servers

---

README.md
doc/openfortivpn.1.in
src/main.c

I believe we need a better solution towards the objective of a single DNS option in the long term.
First revert 6772c53 before we can propose a new patch to perhaps get rid of `--pppd-no-peerdns` as suggested in #328.

Revert 6772c53

---

src/main.c

Typo introduced by bec10e5 has been breaking `--help` output.

Ooops... Fix --help output.

---

src/config.c
src/config.h

carriage returns (that might have come in from copy&paste out of dos/win files) can lead to a damaged config file

treat carriage returns as white space (might solve #129)

---

src/http.c

In `src/http.c:154` the `find_header` function is called with payload `"Transfer-Encoding: chunked"` to detect whether chunked encoding is used.  If the server sends this exact string in the result header, then `find_header` fails to find the header as `line_len` equals `head_len` in that case.

Fix detection of HTTP chunked encoding

---

README.md
doc/openfortivpn.1.in
src/main.c
src/tunnel.c

* The `--set-dns`/`set-dns` option enables either of _pppd_/_openfortivpn_ to get DNS settings from peer _ppp_/FortiGate server and rewrite `/etc/resolv.conf`.
* The `--pppd-no-peerdns`/`pppd-use-peerdns` option switches the above functionality from _pppd_ to _openfortivpn_. This option is not documented any more.
The difference with the previous behaviour is that:
* `--set-dns=0`/`set-dns=0` disables DNS handling in both _pppd_ and _openfortivpn_ instead of _openfortivpn_ only. A single option is now sufficient to avoid messing with `/etc/resolv.conf`.
* `--pppd-no-peerdns`/`pppd-use-peerdns=0` switches DNS handling from _pppd_ to _openfortivpn_. It didn't make sense to have both programs compete to modify `/etc/resolv.conf`, did it? Feels much better this way.
Fixes #328.
This is also a …

Rationalize DNS options

---

src/userinput.c

The way we're setting terminal options when reading password right now means that we're filling the password buffer with non-printable bytes when someone hits backspace or ^U instead of clearing it appropriately.
I've done two versions of this patch, that I left in the commit history:
- the first version naively catches such backspace/^H/^U bytes and tries to handle it; this "works" mostly but won't handle utf-8 characters in the input or weird terminals (although the two bytes I'm comparing should work for most)
- the second version simply does not unset ICANON, I'm not sure why it was unset in the first place (been since the first version of this function) -- not unsetting it means the terminal will handle these as usual (like in a bash 'read' prompt) and will just work™
Please see the …

Handle backspace/^U for password prompt

---

src/http.c
src/ipv4.c

New warnings introduced with recent of version of GCC need ignoring
or fixing.
This is an attempt to fix them.

gcc 8: fix -Wstring-truncation warnings

---

src/main.c

one of the most frequently asked questions that we ask the users who open issues is "can you try to run with -v for verbose output?" and in most cases the next question is "which version of openfortivpn is this?", so it would make sense to include this information in the debug output already.

show version number in debug output

---

src/ipv4.c

Also increase the buffer size as suggested in #342.
The buffer size should probably be set dynamically.

Avoid magic numbers in code

---

Makefile.am
configure.ac
src/tunnel.c

Allows usage of Type=notify systemd service types.
Fixes: #229

Notify tunnel up to systemd with sd_notify

---

src/http.c
src/http.h
src/ipv4.c

On MacOS, `ipv4_get_route` gets stuck in an infinite loop if the buffer is too small. This patch increases buffer size to 64k and adds a sanity check that raises an error instead of locking up.

Increase buffer size  in ipv4_get_route to 64k, add sanity check for overflows in MacOS

---

doc/openfortivpn.1.in
src/config.c
src/config.h
src/http.c
src/main.c
src/tunnel.c
src/tunnel.h

Parse config file and command line arguments in two different variables
and merge them appropriately.
Future work could make the merge function behave differently depending
on environmental circumstances (e.g. openfortivpn run as a setuid
program probably would want to refuse some cli options)
Fixes #258.

config: prioritize cli options to config file

---

configure.ac

on Scientific Linux release 6.10 (Carbon), a RHEL clone maintained at CERN
I have noticed that configure fails with the following error:
checking for LIBSYSTEMD... ./configure: line 4877: syntax error near unexpected token `else'
./configure: line 4877: `else'
if libsystemd is not found. The empty square bracket in configure.ac:
PKG_CHECK_MODULES(LIBSYSTEMD, [libsystemd], [AC_DEFINE(HAVE_SYSTEMD)], [ ])
suppresses a human readable configure error but produces invalid shell code.
Printing out a message that we haven't found libsystemd solves the problem.

fix regression when no systemd is present on linux

---

Makefile.am
README.md
configure.ac
doc/openfortivpn.1.in
etc/ppp/ppp.conf.example
src/config.c
src/config.h
src/io.c
src/ipv4.c
src/ipv4.h
src/main.c
src/ssl.h
src/tunnel.c
src/tunnel.h

I have started this work some time ago. At the current stage I have managed to configure, compile and run _openfortivpn_ on FreeBSD 11.
The last remaining issue is that FreeBSD doesn't have `pppd` anymore and uses a user-space tool called `ppp`. It doesn't take many options from the command line but rather from STDIN or from a config file. To my understanding of the [man page](https://www.freebsd.org/cgi/man.cgi?query=ppp&sektion=8) it should be possible to put all necessary parameters into `/etc/ppp/ppp.conf` and _openfortivpn_ should work with this. If this works, the only missing bit is to provide a working sample configuration and perhaps an update of the man page.
Many command line options of _openfortivpn_ concerning how `pppd` is called are currently not supported on BSD. At a …

FreeBSD support

---

configure.ac

Library libssl depends on libcrypto, not the other way round. This changes the resulting Makefile from "-lcrypto -lssl" to "-lssl -lcrypto".

Natural ordering of OpenSSL libraries

---

src/ipv4.c

this solves #378:
On OSX and FreeBSD there is no /proc file system where we could look up the routes currently configured.  We have to parse the output of the netstat tool. In this output there are also routes which are directly connected to specific interface, e.g. the tunnel interface automatically has a default route attached. When determining the route to the vpn gateway for instance, we need a route which does not go through the tunnel. Therefore we need a way to specify that routes over a particular interface are taken (or explicitly not taken, in this particular case).

improve routing code for Mac OSX and FreeBSD

---

src/main.c

Actual root privileges are required in many places, depending on the OS:
* On Linux, the 'noauth' option of pppd seems to require actual root privileges. Being a meber of the 'dip' group on Ubuntu is not sufficient.
* On Linux, setting routes requires root privileges unless user has CAP_NET_ADMIN capability.
* On FreeBSD, setting routes using 'route' requires root privileges.
Fixes #373.

Bail out if not run as root

---

src/ipv4.c

Use one space around (on each side of) most binary and ternary operators,

Linux kernel coding style

---

src/http.c
src/http.h
src/main.c
src/tunnel.c

Printing "Bad HTTP response" for any HTTP response different from 200 is imprecise and eventually not helpful.
Better error messages might be a compelling reason to use a lightweight 3rd party HTTP library.

Helpful error messages

---

src/http.c
src/ipv4.c
src/log.c
src/log.h

on FreeBSD (and OSX), namely when adding routes via route command

use ppp interface name instead of ip for routing

---

src/http.c

All examples in this reference use upper case for hexadecimals:
https://www.w3schools.com/tags/ref_urlencode.asp
While URL decoding is (hopefully!) case insensitive, let's follow the reference blindly.

HTML URL Encoding Reference uses upper case

---

src/http.c

While debugging some case of #366 I noticed that the value of the `Accept-Encoding` header had a typo.
Fixing the value doesn't make the issue go away but is one less thing which might go wrong.
I also added the fall-back value `*/*` to the `Accept` request header, just in case this might cause some trouble somewhere.

Fix value of Accept-Encoding request header

---

src/http.c

Citing from issue #411:
I have implemented 2FA using Radius+PrivacyIdea and is working quite well.
For openfortivpn, I have found that "try_otp_auth()" does not send 'realm'
information, so connection is dropped even if authentication was successful.
Additional correction of the check for LENGTH_AVAILABLE: Take into account
the length of the additional "&realm="

support realm together with 2FA

---

README.md
doc/openfortivpn.1.in
src/main.c
src/tunnel.c

This reverts commit f3830844090d9107112fb83dd93089da4961add1.
See #349 and #406.
With f383084 it is not possible anymore to use _openfortivpn_'s internal mechanism to update  `/etc/resolv.conf`, because it ***also*** needs to pass the `usepeerdns` option to `pppd` in order to receive this information from the vpn server. Here a symmary of the combinations of the options and the result:
New behavior without specific ip-up scripts for the ppp interface or _openresolv_ service:
| set-dns | pppd-use-peerdns | `/var/run/ppp/resolv.conf` | `/etc/resolv.conf` |
| --- | --- | --- | --- | 
| true | true |  created/updated | **not** updated (default case) |
| true | false |  not created/updated | not updated (**broken**) |
| false | true |  **not** created/updated | not updated |
| false | false | …

Revert "Rationalize DNS options"

---

src/config.c
src/config.h
src/main.c

I was recently hit by #358. I have a password that is length 64. 
Despite [config.h](https://github.com/adrienverge/openfortivpn/compare/master...nknotts:longer-passwords#diff-ebab3775208ceccb934d0d29f384a367R61) defining `struct vpn_config` with `password[FIELD_SIZE + 1];`, [config.c](https://github.com/adrienverge/openfortivpn/blob/3b5a28ca21ed0ee3f56b58828eee78f26402f7af/src/config.c#L170) reads password via
```
strncpy(cfg->password, val, FIELD_SIZE - 1);
cfg->password[FIELD_SIZE] = '\0';
```
Thus, despite password having a length of 65, only 63 bytes would be used. I considered fixing all uses of `FIELD_SIZE` but wanted to start a discussion about it first. 
Increasing `FIELD_SIZE` allows the use of my password and should help alleviate #358. I did not do a deep inspection to …

config.h: set FIELD_SIZE to 128

---

CHANGELOG.md
configure.ac

We have two important fixes on master now (#416 and #399).
I would also like to land #361 just because it is not a big change, hanging around for such a long time (which causes trouble when the branches have diverged too much as we have seen). 
I have that description already in the updated CHANGELOG.md, so before merging this one we should either merge the fix for long passwords or update the high level changelog once again.

openfortivpn version 1.8.1

---

configure.ac

In the rpms for 1.8.1 we did not notice that PPP_PATH was not set properly.
This might have been noticed if there was an output of the value actually used,
so adding those results to the configure output may help avoiding similar
issues in the future.

improve configure output

---

doc/openfortivpn.1.in
src/config.c
src/config.h
src/http.c
src/main.c

* print out OTP prompt starting with 'Enter' (which may contain the index of the code in a list) see #427
* add a config file option (and command line parameter) for that
* rebased the --otp-delay option which is still open in #376

new OTP related options

---

doc/openfortivpn.1.in
src/main.c

In the config file we accept pppd-use-peerdns whereas on the command line only --pppd-no-peerdns is allowed. Usually we have the "--no-xy" options as an alias for a similar "--xy=0" option.
Maybe this helps to clarify the confusion around the dns options?

implement --pppd-use-peerdns command line option for consistency

---

CHANGELOG.md
configure.ac

time to tag a new release?
first I had in mind to tag 1.8.2 with the latest fixes and documentation updates, but when putting together the high level changelog I have noticed that most of the commits contained at least a new command line option or an improvement of an existing feature.  Therefore, we should make it the 1.9.0 release, even though it doesn't contain a very exciting new feature.
Of course we could wait for something, but at least I don't have big things in the queue at the moment.

openfortivpn version 1.9.0

---

src/tunnel.c

While forkpty() does a nice job of convenently setting up a pty for the
pppd, it goes a bit too far for our purposes by also sending stderr to
the pseudoterminal.
This causes confusion in the event pppd (or its plugin, or us, for that
matter) try to log anything to stderr. Let's restore the parent's stderr
after he fork.

tunnel: pass our stderr to the pppd slave

---

src/config.c
src/config.h
src/http.c
src/main.c
src/userinput.c
src/userinput.h

This adds the --pinentry option that allows passing a name of a program
that can supply a password. This is going to be useful in order to relay
the password requestes to the NetworkManager plugin.
The protocol used is compatible with what GnuPG's pinentry program uses
(documented in pinentry GNU Info manual), so that this could be tested
or used without the NetworkManager plugin.

userinput: add capability of spawning a helper to get a secret

---

configure.ac

this helps when cross-compile and we pass --with/--disable arguments instead
of letting configure to find it for us
Signed-off-by: Lucian Cristian <lucian.cristian@gmail.com>

configure.ac: don't check file path if --with/--disable specified

---

configure.ac

when cross compile, running tests will always fail, don't run them when
the option is passed
Signed-off-by: Lucian Cristian <lucian.cristian@gmail.com>

configure.ac: rt_dst: don't run tests when option is passed

---

src/io.c

FreeBSD seems to have the issue that `write()` can return `EAGAIN` even when an immediately preceding `select()` indicated a writable socket.
Work around this issue by retrying.
Note that this creates a potential busy loop around failing `write()`, which this change does nothing to avoid.

work around EAGAIN issue on FreeBSD

---

src/http.c
src/log.c
src/log.h
src/main.c

...and introduce another log level "debug all" to even show the password
for debugging encoding stuff. Currently only the password is cleared,
otp, cookie and perhaps other information during the authentication
process is considered less critical.

suppress cleartext password in debug detail output

---

src/config.c
src/config.h
src/main.c
src/tunnel.c

Openssl 1.1 sets min tls version to 1.2. This prevents me to connect to fortivpn at my work.
I do not want to fiddle with system defaults, thus I added min_tls option. And then I added
seclevel-1 option, because I realised, that compiled-in list of ciphers is sufficient for me.
Inspired by similar wpa_supplicant bug, triggered by libssl1.1
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=907518#95
https://w1.fi/cgit/hostap/commit/?id=cc9c4feccc5588137f66c40a4a6729476556853e

Connect to old TLSv1.0 software - override new openssl defaults.

---

src/config.c
src/tunnel.c

starting with openssl 1.1.0 the library and error strings are
initialized automatically and no explicit initialization is needed anymore
in openssl 1.1.0 tls 1.3 is not yet present, so instead of comparing
version numbers it's better just to check if TLS1_3_VERSION is defined

fix openssl 1.1.x compatibility issues (#448)

---

CHANGELOG.md
configure.ac

Shall we tag a new release? 
I have landed a couple of fixes and improvements of existing features.
The only really new feature this time is the support of the pinentry program, which makes this not a pure bugfix release but indeed adds new functionality and a new command line parameter.

release 1.10.0

---

Makefile.am

I have received this from Mike: --pedantic should correctly be -pedantic

one-byte fix to build with lcc compiler

---

src/ipv4.c

fix for #470
when parsing routing entries with cidr notation, the calculated
mask was shifted in the wrong direction. This has lead to the
result that ipv4_get_route has returned the wrong route in some
cases.

correctly shift masks for cidr notation on MAC

---

README.md
doc/openfortivpn.1.in
src/config.c
src/config.h
src/http.c
src/main.c
src/tunnel.c
src/tunnel.h

Developed for Yubikey, but may work with other PIV enabled smartcards too.

Added smartcard support with openssl-engine

---

src/config.c
src/io.c
src/main.c
src/tunnel.c

Defects detected by the new Coverity Build Tool version 2019.03:
CID 349824: Invalid type in argument to printf format specifier (PRINTF_ARGS)
invalid_type: Argument packet->len to format specifier %d was expected
to have type int but has type unsigned long.
CID 349825: Extra argument to printf format specifier (PRINTF_ARGS)
extra_argument: This argument was not used by the format string:
config_file.
CID 349827: Invalid type in argument to printf format specifier (PRINTF_ARGS)
invalid_type: Argument port to format specifier %d was expected to have
type int but has type unsigned long.
CID 349828: Invalid type in argument to printf format specifier (PRINTF_ARGS)
invalid_type: Argument 128UL to format specifier %d was expected to
have type int but has type unsigned long.
CID 349830: Invalid …

Fix Coverity defects

---

src/tunnel.c

Therefore cannot write:
p->off < ncap - 1
Instead we have to write:
p->off + 1 < ncap
That's infortunate because the documentation reads:
[...] off [...] < max(cap - 1, 1)

'cap' and 'off' are unsigned!

---

doc/openfortivpn.1.in
src/http.c
src/io.c
src/ipv4.c
src/ipv4.h
src/main.c
src/tunnel.c
src/xml.c
src/xml.h

currently we just prepend a search line to resolv.conf when adding nameservers
only the first nameservers take effect and only the last search statement
openfortivpn competes with pppd when manipulating that file

support dns-suffix feature

---

README.md
doc/openfortivpn.1.in
src/http.c
src/main.c

...and with password set to an empty string, which denotes that no password shall be asked or sent
allow username to be empty for smartcard login
update man page and readme

allow logging in with a certificate only

---

CHANGELOG.md
configure.ac

I have prepared the update of  CHANGELOG.md
this PR is based on the branch for #493 and the change assumes that this PR will be merged before tagging the new release. 
We also should consider if we had enough testing. IMHO these critical changes are on the current master:
- smartcard support
- properly handle manipulations of resolv.conf (we had a first attempt of this change of behavior already)
- maybe new defects introduced by #493 because I don't know how to set up a test environment for this kind of authentication

Release 1.11.0

---

configure.ac

AC_TRY_RUN has been replaced by AC_RUN_IFELSE.
Additionally we do not need to run the snippet, just compile it.
Therefore use AC_COMPILE_IFELSE instead of AC_RUN_IFELSE.

Remove obsolete AC_TRY_RUN

---

src/ipv4.c

Forticlient supports semicolon as separator in the dns-suffix and
replaces them by spaces. For consistency openfortivpn should do the same.
This solves #504.

replace semicolon by space in dns-suffix string

---

tests/lint/astyle.sh
tests/lint/eol-at-eof.sh
tests/lint/run.sh

Check exit code directly, not indirectly with $?.
Command which is non-standard. Use builtin 'command -v' instead.
Print error messages to stderr.

Shell fixes

---

doc/openfortivpn.1.in

be more precise in the descrciption on how the digest is formed:
the certificate must be DER encoded, and NOT in PEM form when
deriving the digest

update man page about digest

---

src/main.c

We had another issue in which the password was disclosed. In openfortivpn we suppress it in the -vv output since #443 as a reaction on #407 and we have introduced -vvv as a new verbosity level, but now users submit -vvv debug output without a closer look, so a clear warning at the beginning of the output might help to avoid disclosure by accident.

add a clear warning about sensitive information in the debug output

---

src/http.c

when special characters were contained that need to be url_encoded
the anonymization mechanism did not mask the password in the debug
output of the http request

always hide cleartext password in -vv output

---

src/ipv4.c

this  "Memory - illegal accesses  (USE_AFTER_FREE)" was found by coverity scan

free resolvconf_call after last usage

---

src/http.c
src/main.c

It actually worked because use_engine is intialized to 0 here or -1 elsewhere
and we later test:
use_engine > 0
Yet the expected values seem to be -1 and 1, not 0. Perhaps we should
make use_engine a "boolean" with 0/1 values, but the expected values
clearly seem to be -1/1 for now.

Explicitly initialize use_engine

---

src/config.c
src/ipv4.c
src/tunnel.c

I don't think there are significant cases where _close()_ and friends fail out there. Yet check return value and emit a warning if it ever happens

Check the return value of close()

---

README.md

This is the canonical URL according to this reference page:
https://ports.macports.org/

Fix URL to MacPorts

---

src/hdlc.c
src/hdlc.h
src/main.c

Applied some minor changes while trying to understand and review this source file:
* Const-correctness
* Consistency with RFC 1662 (same vocabulary and use the exact same code for FCS calculation)
* Consistency within file (re-use existing variables such as the pre-calculated checksum)
* Reworked code comments

Consistency in HDLC support

---

src/main.c

While either `HAVE_USR_SBIN_PPPD` or `HAVE_USR_SBIN_PPP` **must** be defined,
`HAVE_RESOLVCONF` might not be defined - typically when _resolvconf_ is not
available at build-time. `RESOLVCONF_USAGE` and `RESOLVCONF_HELP` should always
be defined, if needed as empty strings, so as to not break subsequent
_printf_() calls.

Always define RESOLVCONF_USAGE / RESOLVCONF_HELP

---

src/main.c

Check we have either `HAVE_USR_SBIN_PPPD` or `HAVE_USR_SBIN_PPP`, not both, not none. Just in case.

Extra preprocessor checks

---

configure.ac

On Fedora _resolvectl_ does not work as expected when invoked as `resolvconf`.
Also the exit status is not 0 so the current test never works actually:
```sh
$ resolvconf -a -f ; echo $?
Expected interface name as argument.
1
$ 
```
I suggest this goes in _openfortivpn_ 1.13.2.

Skip resolvectl for now

---

configure.ac

Cosmetic fixes in configure.ac

---

configure.ac

when cross-compiling we should not attempt to run resolvconf,
especially not when it is set to DISABLED. In that case the whole
resolvconf code is not compiled in at all and it does not matter
how the default would be in the disabled code
In #598 I have found the workaround to specify both options 
`./configure --disable-resolvconf --with-resolvconf=DISABLED`
but when the code is disabled anyway by `--with-resolvconf=DISABLED` 
additionally specifying a default with `--disable-resolvconf` should not be necessary

do not check resolvconf again when disabled

---

.travis.yml

It looks like these builds take for ever on Travis CI.
I don't know whether this a temporary problem or not but we have been unable to validate pull requests since this change. WIll revert for now and think about it again...

Disable macOS and FreeBSD builds for now

---

CHANGELOG.md
configure.ac

* [-] fix a coverity warning
* [-] cross-compile: do not check resolvconf on the host system

openfortivpn version 1.13.3

---

tests/ci/install_openssl.sh

The location of old releases has been moved from:
https://www.openssl.org/source/
to:
https://www.openssl.org/source/old/1.0.2/

Fix OpenSSL build

---

Makefile.am

> This special significance of '$' is why you must write '$$' to
> have the effect of a single dollar sign in a file name or command.
See:
https://ftp.gnu.org/old-gnu/Manuals/make/html_chapter/make_6.html#SEC66

Fix Makefile

---

Makefile.am
configure.ac
src/main.c

We update the version number only when we create a new release. When testing different branches, it sometimes makes sense to have a more fine grained hint at which level of the sources a binary was built. The commit id of the git HEAD could be such a little piece that may help to distinguish if it's the released version or if it includes (at least one) more patch(es).

include git commit id as revision in debug output

---

Makefile.am

* Add missing target to "make" `etc/openfortivpn/config`.
* Add missing target to "make clean" `etc/openfortivpn/config`.
* Add missing target to "make uninstall" `$(confdir)/config`.

Standardize Automake use: additional changes

---

Makefile.am
configure.ac

* Be consistent and do not "make uninstall" `$(confdir)/config` as it is not clobbered by "make install" either.
* Silent rules for sed.

Standardize Automake use: final changes

---

src/http.c
src/http.h
src/ssl.h

Prepare for adding an external HTTP library later on.
The pull request will help use external HTTP / XML libraries later on. At this point I am not certain we will benefit from using [PicoHTTPParser](https://github.com/h2o/picohttpparser) in terms of maintainability and less code. Yet I'm opening the pull request to perform some code clean up, add a few assertions here and there, and raise a few issues.
For example we do not catch SSL errors if the header has already been read. Here is the relevant part in the new code:
https://github.com/DimitriPapadopoulos/openfortivpn/blob/230b158/src/http.c#L177-L181
and in the old code:
https://github.com/adrienverge/openfortivpn/blob/8b0c235/src/http.c#L217-L221
@adrienverge Is this on purpose? Are we lenient on purpose? On my machine I have …

Reorganize http_receive()

---

src/io.c
src/ipv4.h
src/xml.c
src/xml.h
tests/lint/line_length.py

Hi,
I found out that printing the dns suffixes could be a first step to enable networknanager-fortisslvpn to scrape this information, and then report it back to whatever handles resolv.conf in NetworkManager. For now this information is not used by pppd.
On the other end, I think adding a stable parsable output would be a more appropriate, proper solution.
Sample output:
```
VPN account password:
INFO:   Connected to gateway.
Two-factor authentication token:
INFO:   Authenticated.
INFO:   Remote gateway has allocated a VPN.
Using interface ppp0
Connect: ppp0 <--> /dev/pts/1
INFO:   Got addresses: [0.0.0.0], ns [0.0.0.0, 0.0.0.0], ns_suffix [sub.example.com example.com]
INFO:   negotiation complete
INFO:   negotiation complete
Cannot determine ethernet address for proxy ARP
local  IP …
```

Add dns suffix information to informative message

---

.gitignore
Makefile.am
configure.ac
lib/systemd/system/openfortivpn@.service.in

Fixes #623.
The `configure.ac` changes are documented in the _systemd_ man page:
https://www.freedesktop.org/software/systemd/man/daemon.html#Installing%20systemd%20Service%20Files
Allows _openfortivpn_ to act as system service.
There are a couple issues that bother me:
* _openfortivpn_ used to be entirely installed under `${prefix}`, including the default configuration file under `$(sysconfdir)/openfortivpn` → `$(prefix)/etc/openfortivpn`. With this change _openfortivpn_ installs its _systemd_ service file outside `$(prefix)`, under `$(systemdsystemunitdir)` → `/lib/systemd/system/`. That's by design of course but I thought I'd mention it.
* I'm not certain I have got the `Makefile.am` right, on the contrary. My concern is conditionals in the Makefile - with/without _systemd_ service …

Add systemd service file

---

src/tunnel.c

Notify that the service is beginning its shutdown (STOPPING=1) in addition
to notifying that service startup is finished (READY=1).
In the future we could perhaps add more events:
STATUS=…
ERRNO=…
See:
https://www.freedesktop.org/software/systemd/man/sd_notify.html

More systemd notifications

---

src/http.c

This should perhaps be tested by someone who actively uses smartcard login without username and password. I remember that usual practice was to have dummy entries in username and password which is a configuration which would be broken by this commit. Anyhow, if those users change their config file to include an empty line for username and password, I would expect it to work again, but I would have a better feeling if someone could confirm this.

allow logging in with smartcard and username+password

---

src/config.h
src/hdlc.c
src/http.c
src/ipv4.h
src/tunnel.c
src/xml.c

* Document some constants
* Move MAX_DOMAIN_LENGTH to config.h
* Consistency in RFC names and links
* Low-level functions should use log_debug()

Small cleanup

---

src/http.c
src/ipv4.c

Avoid GCC extension to fix this warning:
warning: variable length array folded to constant array as an extension [-Wgnu-folding-constant]

Fix Clang warnings

---

Makefile.am

Target 'install-data-hook' should only install the config file.
Do not mess with the systemd service file!
The systemd service file should be guarded with 'if HAVE_SYSTEMD'.

Ooops... Left a spurious dependency behind!

---

src/tunnel.c

fixed `in not in` => `is not in`

typo in log_error

---

src/http.c

FortiGate appliances that are unable to provide configuration
in XML format are probably running FortiOS 4 or earlier which
has been umaintained and vulnerable for some time now.
Warn the user that the FortiGate appliance is outadated and that
it might not be compatible with recent OpenSSL 1.1.1 libraries
with weak ciphers disabled - we've had a case on Ubuntu 20.04 for
example.

Attempt to warn of outdated FortiGate appliances

---

configure.ac
src/http.c

Currently this includes the code to read HTML-formatted configuration
from FortiOS 4. More recent versions send XML-formatted configuration.
In the short term the obsolete code will remain active by default. Then
we will switch to disabling it by default. In the long term it can be
removed.
Fixes #677.

Prepare to get rid of obsolete code

---

configure.ac
src/config.c
src/config.h
src/hdlc.h
src/http.c
src/io.c
src/io.h
src/ipv4.c
src/ipv4.h
src/log.c
src/log.h
src/main.c
src/ssl.h
src/tunnel.c
src/tunnel.h
src/userinput.c
src/userinput.h

Use C99 headers instead of POSIX headers when possible:
* size_t is defined in <stddef.h>
* ssize_t still requires <sys/types.h>
* int_8 is defined in <stdint.h>
Reorganize header inclusion:
1. openfortivpn headers
2. 3rd party library headers (OpenSSL, systemd, etc.)
3. POSIX headers
4. C headers

Use C99 standard headers

---

src/tunnel.c

The existing code does work for cipher negotiation with old (FortiOS 4?) FortiGate appliances, but not for personal certificates (SHA-1 certificates).
Two reasons I can see:
* SSL_set_cipher_list() was called **after** messing with certificates.
* SSL_set_cipher_list() applies only to the SSL connection, not to certificates, call SSL_CTX_set_cipher_list() on context instead.
This change addresses both of the above issues.
See [SSL(7)](https://www.openssl.org/docs/man1.1.1/man7/ssl.html#DATA-STRUCTURES) man page:
> **SSL_CTX** (SSL Context)
> This is the global context structure which is created by a server or client once per program life-time and which holds mainly default values for the **SSL** structures which are later created for the connections.
> 
> **SSL** (SSL Connection)
> This …

Set the TLS security level early and on context

---

src/hdlc.h

In C99:
* uint8_t is defined in <stdint.h>
* size_t is defined in <stddef.h>
In POSIX:
* ssize_t is defined in <sys/types.h>

<unistd.h> is not needed

---

src/http.c
src/io.c

The SSL-VPN may allow web mode but not tunnel mode.
In that case it sends an HTTP 403 error back to VPN
clients instead of the expected PPP header.
Catch that case and emit a meaningful error message.
Fixes #689.

Better error message when tunnel mode is forbidden

---

src/io.c

I have nothing against "goto", at least for error handling,
but we had a mixture of "goto" and "break" here.
I chose "break" over "goto" for consistency between ssl_read()
and ssl_write().

goto → break

---

src/io.c

The gateway may return a 403 HTTP error not only when tunnel mode is not enabled, but also when the realm is incorrect.
See https://github.com/adrienverge/openfortivpn/issues/689#issuecomment-625131878.

Suggest broader scope of causes in error message

---

src/config.c
src/main.c
src/tunnel.c

Option SSL_OP_NO_SSLv3 is deprecated as of  OpenSSL 1.1.0, use SSL_CTX_set_min_proto_version() instead.
[List of SSL OP Flags](https://wiki.openssl.org/index.php/List_of_SSL_OP_Flags#Protocol_Version_Options)

SSL_OP_NO_SSLv3 is deprecated

---

src/tunnel.c

We want to avoid deprecated functions whether they're hidden or not.
OPENSSL_API_COMPAT just hides deprecated macros.
Check OPENSSL_VERSION_NUMBER and get rid of deprecated functions.
See also:
[Library Initialization](https://wiki.openssl.org/index.php/Library_Initialization)

OPENSSL_API_COMPAT → OPENSSL_VERSION_NUMBER

---

src/ipv4.h

BSD headers are not self-sufficient, they may require other headers to
be included first. See complete analysis here:
https://github.com/adrienverge/openfortivpn/pull/699#issuecomment-625780460

Put back <sys/types.h> for FreeBSD and macOS

---

src/ipv4.h

`<sys/mutex.h>`  defines mtx_* functions
`<net/if.h>`     defines if_* functions and if_nameindex structure
`<net/if_var.h>` ?

These headers are not needed, even on FreeBSD

---

configure.ac
src/tunnel.c

`<libutil.h>`   needed in `tunnel.c` (but not in `tunnel.h` as previously) to
define _forkpty()_
This function is really not standard.
On Linux it can be found in `<pty.h>`:
[OPENPTY(3)](http://man7.org/linux/man-pages/man3/forkpty.3.html)
On Solaris it can be found in `<termios.h>`:
[forkpty (3C)](https://docs.oracle.com/cd/E88353_01/html/E37843/forkpty-3c.html)
And on FreeBSD, it can be found in a handful headers, as usual:
[PTY(3)](https://www.freebsd.org/cgi/man.cgi?query=forkpty&sektion=3l)
> ### SYNOPSIS
> ```
>      #include <sys/types.h>
>      #include <sys/ioctl.h>
>      #include <termios.h>
>      #include <libutil.h>
> ```

Partial revert: header needed on FreeBSD after all

---

src/ipv4.c
tests/lint/checkpatch.sh

Array size was short by one byte for the terminal `"\n"`.
This bug has been partly introduced by c81fde1 for arrays `ns1` and `ns2` but was already present for `dns_suffix`, which had confused me.
Anyway, this confusion precisely shows that c81fde1 was a good idea!

Fix SIGILL because of out of bounds array access

---

src/ipv4.c

if the route is configured through the tunnel it breaks the tunnel itself
this fixes #729

do not accept a route to the vpn gateway

---

src/config.c
src/config.h
src/http.c

These changes add support for Fortinet's hostchecks.
Also, the useragent is configurable. Newer Forti firmware doesn't recognise the old UA
Configuration items are as follows:
```bash
##
##
#user-agent = FortiSSLVPN (Windows NT; SV1 [SV{v=02.01; f=07;}])
##
```

Added support for hostchecks

---

doc/openfortivpn.1.in
src/config.c
src/config.h
src/http.c
src/main.c

In our organization, the fortinet server is configured to be able to send a push notification to the FortiToken app. I figured I could give it a shot to add this feature to this client :).
Checking the requests the official client sends for this, I found it sends `ftmpush=1` instead of the `code=<OTP>&code2=` data in the `logincheck` post.
I've done my best to keep the code around this as clean as I could, but my C++ isn't that strong.  
The code does what I want it to do though; it sends me a push notification if I don't pre-configure the OTP, and uses the given OTP if I run `openfortivpn` with the `--otp=<OTP>` option.

Extend OTP support to also allow using FTM push

---

src/main.c

Some other programs like mysql do it. It's not 100% safe. One can still view it in output of `ps` **if** invoked at the _right_ time.

Destroy password supplied via CLI

---

src/io.c

"written += n" in the case that n==-1 and errno == EAGAIN causes "written" to go backwards. continue, instead, to avoid updating it in the retryable write case.

#754 io.c: pppd_write() - continue on EAGAIN

---

src/http.c

OTP is used when the user has a fortitoken in advance and can set it in the config file or via the command line, so that it is available before login. 2FA are requested after login, sent by email or SMS. 
It makes sense to name the hint differently, and helps distinguish both cases case forthe benefit of NetworkManager-fortisslvpn and derivatives

Use different hints for OTP and 2FA

---

configure.ac
doc/openfortivpn.1.in
src/config.c
src/config.h
src/main.c
src/tunnel.c

On multiple interface devices, it can be necessary to bind the VPN to a specific network interface. This can be necessary in situations where you have multiple interfaces and need to connect the VPN on a secondary interface. This feature is supported in openconnect, and would be useful in openfortivpn.

Add command line option to bind to a specific network interface

---

src/userinput.c

The pinentry program answers with "D PIN\nOK\n". Sometimes the "\nOK\n" gets sent to the gateway, causing errors. The change ensures only the PIN is sent, by taking the string up to, and discarding, the first "\n". See https://github.com/adrienverge/openfortivpn/issues/744

Ensure only the pin code is sent

---

src/io.c
src/tunnel.c

We want to compare their value between platforms to investigate TCP keepalive discrepancies.
Fixes #795.

Print part of the default SSL socket options

---

src/ipv4.c

CID 360865: 'Constant' variable guards dead code (DEADCODE)
dead_error_line: Execution cannot reach this statement:
if (pclose(file) == -1)

Fix Coverity defect

---

src/tunnel.c

For code that is not involved in actual operations, a warning is good enough: the issue can be reported and fixed in later versions, but it shouldn't stop actual operations.
Fixes #822, at least temporarily until we find which _optname_ arguments are supported on mac0S and how to identify them.

Don't raise an error when debug code fails

---

src/tunnel.c

While on Linux the _speed_ option does not seem to be taken into account, on macOS it appears to be throttling the VPN connection.
According to the [`pppd` man page](https://ppp.samba.org/pppd.html), Linux and other system "only support the commonly-used baud rates". However, `pppd` does not require specific baud rates in this use case.
Fixes #428?

Hopefully help reach higher speeds on macOS

---

src/config.c
src/config.h
src/http.c
src/main.c
src/tunnel.c

Revert #361. Replace `FIELD_SIZE` by more specific variables. Use a maximum length of 256 characters for `password`.
Fixes #826.

Revert from dynamic to automatic allocation of password

---

src/tunnel.c

While the 192.0.2.0/24 TEST-NET-1 block would avoid collisions,
the 169.254.0.0/16 subnet described in RFC3927 has precisely been
specified precisely for such cases.
We should probably select "an address using a pseudo-random number
generator with a uniform distribution in the range from 169.254.1.0
to 169.254.254.255 inclusive", as described in RFC3927. However,
that would of course require more code and I'm lazy, but more
importantly it had been reported that FortiClient uses 169.254.2.1.
I'd rather use the same address as FortiClient.
Fixes #832.

Assign an IPv4 address from the link-local subnet

---

src/http.c

Other prompts do have that final space:
```
"VPN account password: "
"Two-factor authentication token: "
```
@mrbaseman I cannot test myself, but this makes sense, doesn't it?

Add a space at the end of the OTP prompt

---

doc/openfortivpn.1.in
src/config.c
src/config.h
src/main.c
src/tunnel.c

OpenSSL queries for the PEM pass phrase whenever we call ssl_connect().
Instead, openfortivpn will query for the PEM password only once, if needed, from within an OpenSSL callback.

Query for the PEM pass phrase only once

---

src/tunnel.c

Helps to compile against OpenSSL with `no-engines` option. Fixes https://github.com/adrienverge/openfortivpn/issues/793
Original commit author @The-BB.
* Compile tested: `openfortivpn` 1.15.0/1.16.0 against `openssl` 1.1.1h, mips/mipsel/x86/x64 archs, kernel 2.6/3.2/3.4 based toolchains,
* Run tested: @Entware repo, mips target.

Optional OpenSSL engines usage

---

src/tunnel.c

On macOS, SO_SNDBUF and SO_RCVBUF are defined in <sys/socket.h> but
getsockopt() fails for these values with:
Protocol not available
I guess this is expected on macOS, although the GETSOCKOPT(2) man page
does not document that. In any case the behaviour is common enough to
avoid the warning in the log.
Fixes #822.

Avoid spurious warning on macOS

---

src/tunnel.c

To honor bundle of chained client certificates, prefering  SSL_CTX_use_certificate_chain_file over SSL_CTX_use_certificate_file could come handy, as stated in https://www.openssl.org/docs/man1.0.2/man3/SSL_CTX_use_certificate_file.html.

Prefer SSL_CTX_use_certificate_chain_file

---

tests/ci/install_openssl.sh

OpenSSL 1.0.2u is the latest publicly available release.
OpenSSL 1.0.2y is currently the latest security fix for version 1.0.2, available under extended support contracts. We do not have access to it, so we stay with 1.0.2u.

Upgrade to the latest OpenSSL 1.0.2 release

---

.github/workflows/openfortivpn.yml

Otherwise, we end up running tests twice with each pull request, first when submitting the pull request, then when pushing the pull request into master.

Ignore pushes to master branch

---

src/tunnel.c

From the man page:
SSLv23_method(), SSLv23_server_method(), SSLv23_client_method()
Use of these functions is deprecated. They have been replaced with
the above TLS_method(), TLS_server_method() and TLS_client_method()
respectively. New code should use those functions instead.

SSLv23_client_method() → TLS_client_method()

---

README.md
doc/openfortivpn.1.in

Based on the discussion in https://github.com/adrienverge/openfortivpn/issues/710
- Add missing `--pinentry` option to man page
- Improve the man page on plain password vs. pinentry
- README to mention man page as the main source of documentation
- README to favor pinentry over plain text passwords
- Fix format of headers in README
----
The changed parts of man page after local `sudo make install`:
```
OPENFORTIVPN(1)
NAME
openfortivpn - Client for PPP+SSL VPN tunnel services
SYNOPSIS
openfortivpn  [<host>[:<port>]]  [-u  <user>]  [-p  <pass>]  [--pinentry=<name>]  [--otp=<otp>]  [--otp-prompt=<prompt>] [--otp-delay=<delay>] [--no-ftm-push] [--realm=<realm>] [--ifname=<interface>] [--set-routes=<bool>]
[--no-routes] [--set-dns=<bool>] [--no-dns] [--half-internet-routes=<bool>] …
```

Document secure password storage with pinentry

---

doc/openfortivpn.1.in

According to man-pages(7), conventional man page section names include CONFIGURATION but not CONFIG FILES. On the other hand CONFIGURATION is `Normally only in Section 4` _Special files (devices)_. Still, I prefer standard names.

CONFIG FILES → CONFIGURATION

---

configure.ac

* While the _malloc_() and _realloc_() functions are being called, the _AC_FUNC_MALLOC_ and _AC_FUNC_REALLOC_ macros have already been checking if these functions are available **and** compatible with the GNU C library functions.
* Also, _optarg_ and _optind_ are not functions - they are documented to be external variables.

Remove unused functions from AC_CHECK_FUNCS

---

Makefile.am

While it makes sense to use **CFLAGS** consistently, `OPENSSL_CFLAGS` and `LIBSYSTEMD_CFLAGS` define header inclusion paths, therefore they should be appended to `CPPFLAGS`.

Revert 89615fc

---

configure.ac

I don't think we need AC_FUNC_MALLOC and AC_FUNC_REALLOC.
From the [documentation](https://www.gnu.org/software/autoconf/manual/autoconf-2.70/html_node/Particular-Functions.html):
> If the `malloc` function is compatible with the GNU C library `malloc` (i.e., ‘`malloc (0)`’ returns a valid pointer), define `HAVE_MALLOC` to 1. Otherwise define `HAVE_MALLOC` to 0, ask for an `AC_LIBOBJ` replacement for ‘`malloc`’, and define `malloc` to `rpl_malloc` so that the native `malloc` is not used in the main project.
We do not rely on this specificity as far as I can see.

Do we really require GNU C library compatibility?

---

configure.ac

Do not read the HTML-formatted configuration from FortiOS 4.
Just read the XML-formatted configuration.
#680 was the 1st step.
This is the 2nd step.
The 3rd step will be to completely get rid of the obsolete code and the `--enable-obsolete` option.

Disable support for FortiOS 4 by default

---

CHANGELOG.md
configure.ac
src/ipv4.c

We should probably integrate [codespell](https://github.com/codespell-project/codespell) into CI:
[Integrating codespell into your CI](https://belmoussaoui.com/article/14-integrate-codespell-ci)

Typos caught by codespell

---

src/io.c

The type of `total` is `uint16_t`, so it's 65535 at most.
The type of size is `uint16_t` too, but in addition we have:
```
total == 6 + size
```
So `size` is 65529 at most and cannot be `0xffff`. So far, LGTM seems to be right when suggesting removing the comparison.
So, why does Coverity Scan still complain? The following failure might be possible:
* `total` < 6
* `size` > 65529 and operation `6 + size` overflows
While comparing `size` with `0xffff` does seem useless, we do add a check to make sure that `total >= 6`, which may happen if an attacker sends a crafted packet.

Rework 6a2873b

---

src/tunnel.c

Actually, I have not entirely reverted #846 / e9dfa8e. I have just modified the default setting: OpenSSL engines are now enabled by default, but are disabled when `OPENSSL_NO_ENGINE` is set.
Indeed, `OPENSSL_NO_ENGINE` is never defined, while `OPENSSL_NO_ENGINE` may be defined by _OpenSSL_ in `<openssl/opensslconf.h>`.
Fixes #931 and #793.

Revert #846 / e9dfa8e

---

src/config.c

CID 373615: Invalid printf format string (PRINTF_ARGS)
format_error: Invalid conversion specifier in %l".

Fix Coverity defect introduced by working around CodeQL false positive

---

src/tunnel.c

Avoid pointer syntax when possible.
They are different, the array syntax generates smaller, faster code.
See for example [Declaring C String Constants The Right Way](https://eklitzke.org/declaring-c-string-constants-the-right-way):
> ### Pointer Semantics vs. Array Semantics
> 
> I mentioned this in passing already, but the key thing about a pointer is that it has its own memory address. A pointer is not the thing it points to, it's a separate thing entirely. This is _not_ true of an array: an array _is_ the data.
> 
> If you take the address of a pointer, you get the memory location of the pointer itself. If you want to know the memory address the pointer points to, you take the value of the pointer.
> 
> Arrays are not pointers. They are just data. There's no difference between the …

Declare C string constants using array syntax

---

src/http.c

Report to next minor version - not in a patch release.
Revert ef8ee6e421b1d6c2b0a1f6ae00a7e45074371bfc.

Do not print HTTP requests after all

---

src/config.c

* No need for `stat` now that we use `getline()`.
* Always restore `errno` to prior value if `fclose()` fails.

Improve error handling in #952

---

configure.ac

Fixes #982.
See [4.7 Creating Configuration Files](https://www.gnu.org/savannah-checkouts/gnu/autoconf/manual/autoconf.html#Configuration-Files).

Ubuntu 22.04: update to autoconf 2.71

---

doc/openfortivpn.1.in
src/config.c
src/config.h
src/http.c
src/http.h
src/main.c
src/tunnel.c
src/userinput.c
src/userinput.h

Some users are required to login with SAML and perform multi-factor authentications. In some cases performing the authentication without a browser is close to impossible, so it is best to delegate the operation to external programs.
This also allows to move the complexity of dealing with different SAML providers out of `openfortivpn`.
These changes allow users to authenticate in two different ways:
- Passing a valid `SVPNCOOKIE` through a new command line argument (`--cookie`).
Users are in this case expected to know how to retrieve the cookie.
This option is not strictly related to SAML, even though that is likely the main reason for using it.
- ~Specifying a command that will be executed to retrieve the `SVPNCOOKIE` (`--saml-handler`).
The command will receive the URL for the SAML …

Allow to delegate the authentication to external programs

---

doc/openfortivpn.1.in

`--use-peer-dns` → --`pppd-use-peerdns`

Fix typo in man page

---

configure.ac
src/http.c

Do support FortiOS 4 legacy VPN configuration format. The configuration has been sent in XML format since FortiOS 5.
This obsolete code has been disabled in recent openfortivpn versions, and is missing from OpenConnect too. No has been complaining about it, so it is time to remove it!

Get rid of obsolete code

---

.github/workflows/codeql-analysis.yml

CodeQL Action v1 will be deprecated on December 7th, 2022.
For more information, see https://github.blog/changelog/2022-04-27-code-scanning-deprecation-of-codeql-action-v1/

Upgrade CodeQL Action: v1 → v2

---

src/ipv4.c

Hi,
Currently **openfortivpn** tries to set duplicate routes and fails with "WARN:   Route to gateway exists already.".
These changes tries to filter out duplicates and only set unique routes.

fix: only try to set unique routes

---

src/tunnel.c

I do not understand `ipcp-accept-local` would be required or have any effect here:
> With this option, pppd will accept the peer's idea of our local IP address, even if the local IP address was specified in an option.
Indeed, we do not specify the local IP address:
> `":169.254.2.1", // <local_IP_address>:<remote_IP_address>`
Instead, we explicitly ask the peer to provide the local IP address, using option `noipdefault`:
> With this option, the peer will have to supply the local IP address during IPCP negotiation (unless it specified explicitly on the command line or in an options file).
It seems to be working in practice. So let's test it.
Fixes #920.

Fix "Peer refused to agree to our IP address"

---

.github/workflows/openfortivpn.yml

https://docs.github.com/en/actions/using-jobs/assigning-permissions-to-jobs
The idea is that the software supply chain relies on 3rd party actions that could be compromised. Mitigate this risk by giving these actions minimal rights to the repository. Here read-only access is good enough.

Security hardening for GitHub Actions

---

src/tunnel.c

https://github.com/adrienverge/openfortivpn/security/code-scanning/26
> This call to SSL_get_peer_certificate is not followed by a call to SSL_get_verify_result.

Silence CodeQL alert

---

src/main.c

Free items prior to assigning again with `strdup()`, just in case the same option is passed multiple times.

Free `cli_cfg` items prior to assigning

---

src/ipv4.c

```
src/ipv4.c:208: ERROR: "foo * bar" should be "foo *bar"
total: 1 errors, 0 warnings, 1414 lines checked
error: src/ipv4.c does not comply with Linux kernel coding style
```
Strangely enough, this reverts 0157f73 which was suggested by `checkpatch.pl` itself at the time!

Fix new checkpatch.pl issue

---

src/hdlc.c

When start is exactly 2 bytes before the end of the buffer, the optimisation where we skip the last 2 bytes kicks in, and we return an invalid result (offset 0 represents an empty HDLC frame) instead of `ERR_HDLC_NO_FRAME_FOUND`.
Fixes #788.
Thank you @mr0mr0 for this fix!

Discard invalid empty HDLC frame at end of buffer

---

src/ipv4.c

From the POSIX documentation for the `protocol` argument of `socket`:
https://pubs.opengroup.org/onlinepubs/9699919799/functions/socket.html
> Specifies a particular protocol to be used with the socket. Specifying a _protocol_ of 0 causes _socket_() to use an unspecified default protocol appropriate for the requested socket type.
While the actual value of `IPPROTO_IP` is 0, the POSIX documentation for the `netinet/in.h` header suggests `IPPROTO_IP` should be used only for the `level` argument of `getsockopt` and `setsockopt`:
https://pubs.opengroup.org/onlinepubs/9699919799/basedefs/netinet_in.h.html
> The _<netinet/in.h>_ header shall define the following macros for use as values of the _level_ argument of [_getsockopt_()](https://pubs.opengroup.org/onlinepubs/9699919799/functions/getsock …

IPPROTO_IP → 0

---

.github/workflows/codespell.yml

Caused by updated codespell dictionaries.
See also https://github.com/codespell-project/codespell/issues/2786.

Skip new codespell false positives

---

lib/systemd/system/openfortivpn@.service.in

Removed from systemd in 2013.
Addresses https://github.com/adrienverge/openfortivpn/commit/5c71e1f05a661317ad36249771aa3659ee30f04e#commitcomment-111887525.

syslog.target is obsolete

---

tests/lint/line_length.py

* Use faster f-strings instead of format().
* UTF-8 is the default encodign in Python 3.

Improve Python test script

---

tests/lint/astyle.sh
tests/lint/checkpatch.sh

* Use $() instead of ``
* From the [Bash Reference Manual](https://www.gnu.org/software/bash/manual/html_node/Exit-Status.html):
> Exit statuses fall between 0 and 255, though, as explained below, the shell may use values above 125 specially.

Improve Bash test scripts

---

src/config.c
src/config.h
src/hdlc.c
src/hdlc.h
src/http.c
src/http.h
src/io.c
src/io.h
src/ipv4.c
src/ipv4.h
src/log.c
src/log.h
src/main.c
src/ssl.h
src/tunnel.c
src/tunnel.h
src/userinput.c
src/userinput.h
src/xml.c
src/xml.h
tests/lint/astyle.sh
tests/lint/checkpatch.sh
tests/lint/eol-at-eof.sh
tests/lint/line_length.py
tests/lint/run.sh

Stubbornly stick to the examples provided in:
§ 4.2.2 of the [_Compendium of Copyright Office Practices, first ed._](https://copyright.gov/history/comp/compendium-one.pdf)
§ 1005.01(c) of the [_Compendium of Copyright Office Practices, second ed._](https://copyright.gov/history/comp/compendium-two.pdf)
§ [2204.4(A)](https://copyright.gov/comp3/chap2200/ch2200-notice.pdf#%5B%7B%22num%22%3A40%2C%22gen%22%3A0%7D%2C%7B%22name%22%3A%22XYZ%22%7D%2C76%2C151%2C0%5D) of the [_Compendium of Copyright Office Practices, third ed._](https://copyright.gov/comp3/)
> #### 2204.4(A) Variants for the © Symbol
> 
> A variant of the symbol © is acceptable only if it resembles the © closely enough to
> indicate clearly that the variant is intended to be the copyright symbol. Acceptable
> variants include:
> * …

Variant for the © symbol: (C) → (c)

---

src/tunnel.c

Since https://github.com/ppp-project/ppp/commit/9fe8923419a954fedf8b6d1a6cc07b45f165c1ab, pppd refuses to accept a different remote IP if we explictly pass one on the command line. This results in an error like:
pppd: Peer refused to agree to his IP address
Passing ipcp-accept-remote disables this behavior.
Bug: https://bugs.gentoo.org/907404

Pass ipcp-accept-remote to pppd

---

src/config.c
src/config.h
src/main.c
src/tunnel.c

With 3b54df0, macOS users massively report this issue:
```
WARN:   Could not get current default route (Parsing /proc/net/route failed).
WARN:   Protecting tunnel route has failed. But this can be working except for some cases.
```
See https://github.com/adrienverge/openfortivpn/issues/1118.
With 3b54df0, NetworkManager users on Linux report routing problems.
See https://github.com/adrienverge/openfortivpn/issues/1120.
Without 3b54df0, users on Linux with PPP 2.5.0 report this issue:
```
Peer refused to agree to his IP address.
```
See https://github.com/adrienverge/openfortivpn/issues/1114.
Therefore, make the code optional, to cover all cases. Of course, this is a short term solution. We need to understand what happens and provide a real fix that doesn't involve options.
Fixes #1118 and …

Partially revert 3b54df0, make its code optional

---

src/io.c

On some (all?) non-Linux systems, when select() returns pty master file descriptor as ready to read, subsequent read() returns 0 if the slave side fd has been closed, to indicate EOF. When this happens, break is the correct course of action to avoid a potentially hazardous loop.
Fixes github issues #794, #137

Break on reading 0 from ppp pty

---

src/io.c
src/ipv4.c
src/tunnel.c

* Call calloc() instead of malloc()/memset().
* Set pointer to NULL after free(), when not a local variable.

Minor changes for memset() and free()

---

src/config.c

This commit modifies the `merge_config` function to include the 'tun' value from the source configuration if it is set. Previously, this value was not being merged, leading to inconsistencies in the final configuration.
The change checks if 'tun' in the source configuration is different from its default value before merging it into the destination configuration.
This ensures that the 'tun' setting is correctly propagated when configurations are merged, allowing for more flexible and accurate VPN setups.

Merge 'tun' config value if set in source configuration

---

etc/ppp/ip-down.local.example
etc/ppp/ip-up.local.example
tests/lint/astyle.sh
tests/lint/checkpatch.sh
tests/lint/eol-at-eof.sh
tests/lint/line_length.py
tests/lint/run.sh

Hi
According to [Stackoverflow](https://stackoverflow.com/questions/10376206/what-is-the-preferred-bash-shebang#10383546) and [Stackoverflow](https://stackoverflow.com/questions/7670303/purpose-of-usr-bin-python3-shebang) it looks like the portability of the scripts could be improved by having this new style for the shebangs.

Use bash and python3 from env

---

src/http.c

As discussed in private, this commmit fixes issues with masking the password in the debug output. 
Thanks to Moses Palmér from New Rain Software for his report:
When debug logging HTTP requests, openfortivpn makes an attempt to mask the password. This is performed by searching for the URL-encoded password in the log message, and if found, masking its characters.
I see two problems with the implementation.
Firstly, the code assumes that only one instance of the password string is present in the log buffer; if a user has selected a password that may be a substring of a header, the actual password from the query string will be logged.
Secondly, even if the correct instance of the password string is found, it may not be completely masked. The code performing the masking uses the length of the …

fix issues with masking password in debug output

---

configure.ac
src/tunnel.c

PPP ≥ 2.5.0 requires this option to avoid this error:
```
Peer refused to agree to his IP address
```
It makes sense to let the remote decide for the remote IP address.
Unfortunately, PPP < 2.5.0 does not like this option. Of course, it doesn't make any sense.
Fixes #1076.

Add "ipcp-accept-remote" pppd option

---

src/main.c

This is a first step towards removing this option.

Warn when passing deprecated option `--plugin`

---

tests/lint/line_length.py

* Write to `sys.stderr` in the hope the error message will show up in the CI job output.
* Start enumerate at 1 instead of 0, to show the correct line number.

Fix line length linter

---

configure.ac

* Right hand help string starts with lower case for consistency.
* Document only one of `--enable-*` or `--disable-*`, depending on the default value.

Clean up configure.ac

---

src/main.c

This seems required after all.

Revert 4ae6e53

---

configure.ac
doc/openfortivpn.1.in
src/config.c
src/main.c
src/tunnel.c

Runtime option `pppd-accept-remote` will remain available at all time, but will now accept a boolean argument:
* `--pppd-accept-remote=1`: invoke pppd with the `ipcp-accept-remote` option, which is required by pppd ≥ 2.5.0.
* `--pppd-accept-remote=0`: invoke pppd without the `ipcp-accept-remote` option, which is required by pppd < 2.5.0.
* `--pppd-accept-remote` is kept as a deprecated, undocumented synonym of `--pppd-accept-remote=1`.
Build-time option `--enable-legacy-pppd` will change the default from `--pppd-accept-remote=1` to `--pppd-accept-remote=0`. This might be preferable on older platforms shipping pppd < 2.5.0, such as macOS.

Clean up 1a6d2e9

---

README.md

The intended audience is packagers who target platforms shipping pppd < 2.5.0.

Document new configure option `--enable-legacy-pppd`

---

src/config.c
src/config.h
src/main.c
src/tunnel.c

Deal with `sni` the same way as `gateway_host`
- Use the same maximum length `GATEWAY_HOST_SIZE`.
- Handle `sni` as a fixed-length array instead of a pointer to dynamically allocated memory. Fix the current segfault in the process, which can be explained by improper handling of the allocated memory in `merge_config()`, where we would try to merge fixed-size arrays instead of pointers to allocated memory. Now we try to merge fixed-size arrays everywhere.

Fix segfault from my last SNI changes

---

CHANGELOG.md
src/tunnel.c

Remove `getsockopt()` calls introduced in #799 to investigate the possible relation of TCP keep-alives with random disconnections.
The retrieved values did not help, they only confuse us. I believe everything happens at the PPP level, with options `lcp-echo-interval` and `lcp-echo-failure`. See https://github.com/adrienverge/openfortivpn/issues/1187#issuecomment-1868460154.

Remove debugging code

---

src/ipv4.c
src/userinput.c

The output of` /usr/sbin/netstat` would have to be larger than 2 GB for this to be a menace. Because this seems quite improbable, address with an `assert()` for now.

Address integer overflow reported by a code analyser

---

doc/openfortivpn.1.in
src/ipv4.c
src/userinput.c

This reverts commit 0f70bb77a1b2d70f5747c38f83b20b25be6759ad.
Not sure it fixed anything, while it does create new issues in Coverity Scan.

Revert "Address integer overflows reported by a code analyser"

---

configure.ac

We stopped using that header file in #701 / 0952b37.

Get rid of autoconf <net/if_var.h> test

---

configure.ac

These headers are available, but they won’t be found on earlier macOS versions due to requirement for inclusion order.

configure.ac: fix header checks for macOS

---

configure.ac
src/userinput.c

Support older mac0S versions that lack vdprintf().
Fixes #1223.

vdprintf() → vsnprintf()

---

src/http.c

Hi,
After I encounter an issue on my Fortigate following FortiOS upgrade from 7.2.8 to 7.4.4 (see the issue I openned: [here](https://github.com/adrienverge/openfortivpn/issues/1233)). 
My investigation leads me to think that now Fortigate > 7.2.4 doesn't support any content when issuing login request on "/remote/login" and so "Content-length" must be 0. This is confirmed by the debug logs on the firewall saying `do_http_validate:447 Content-Length (11) on uri (/remote/login) not allowed` and by observing Forticlient requests content on Windows using Burp proxy that have no content.
So I'm proposing this pull request to fix the issue on newer Fortigate version where GET request on "/remote/login" is now sending nothing instead of "cert=&nup=1".
This has been tested on a Fortigate 500E …

Patch certificate login error for FortiOS 7.4.4

---

src/main.c

When `--persistent=>0` the OTP should be cleared from the configuration, because it's a one-time password as the name suggests and is probably not valid anymore.
Should there be an option to keep the OTP valid until a certain amount of time has lapsed, since TOTPs may still be valid?

Clear OTP after initial run. Fixes #1244

---

Makefile.am
README.md
configure.ac
doc/openfortivpn.1.in
src/config.c
src/config.h
src/hdlc.c
src/http.c
src/http.h
src/http_server.c
src/http_server.h
src/ipv4.c
src/main.c
src/tunnel.c
src/userinput.c

This pull request is based on https://github.com/adrienverge/openfortivpn/pull/1219, but has everything unrelated to SAML removed and all the review issues fixed.

Support SAML authentication

---

src/http.c
src/main.c

Rework 52148b7 to clear the otp just after it is used.
Also, clear it completely with memset().

Clear otp after each run

---

CHANGELOG.md
configure.ac

@DimitriPapadopoulos @mrbaseman are you OK with this?
Would you prefer to include more changes in this release?
If not, are you OK with the changelog?
Thanks in advance!

openfortivpn 1.23.0

---

src/userinput.c

```
src/userinput.c: In function ‘read_from_stdin’:
src/userinput.c:373:15: warning: unused variable ‘output’ [-Wunused-variable]
373 |         char *output;
|               ^~~~~~
```

Address GCC warning

---

src/tunnel.c

Obviously, this is a workaround, not a fix. A real fix would involve reading the response in chunks, or alternatively allocating a buffer large enough to accommodate the response, after getting `Content-Length` from the response header.
Work around for #1282.

Increase the maximum size of the proxy response

---

src/ipv4.c

CID 456638 Overflowed integer argument (INTEGER_OVERFLOW)
`buffer_size - total_bytes_read - 1UL`, which might have underflowed, is passed to `read()`.

Work around Coverity false positive
