README.md
Add kernel modules and Gentoo Linux requirements.
Add a sample additional file for sudo.
=> Complete the README file

Makefile.am, doc/openfortivpn.1, src/config.h, src/http.c, src/log.c, src/main.c, src/tunnel.c
A couple of fixes and addition of --plugin option that potentially makes it possible to hook the tool to NetworkManager.
=> Some improvements

src/http.c, src/tunnel.c, src/tunnel.h
Verified against a mock-up server and a FortiOS 5 instance.
=> http: some more fixes

src/http.c, src/io.c, src/ipv4.c, src/tunnel.c, src/xml.c, src/xml.h
And fix two issues in the original split VPN patchset.
=> Extend the split VPN support with older FortiOS servers

.travis.yml, LICENSE.OpenSSL, Makefile.am, configure.ac, src/config.c, src/hdlc.c, src/hdlc.h, src/http.c, src/io.c, src/ipv4.c, src/ipv4.h, src/main.c, src/ssl.h, src/tunnel.c, tests/lint/astyle.sh, tests/lint/eol-at-eof.sh, tests/lint/line-length.sh, tests/lint/run.sh
This will ease the future reviewing process.
=> Add CI integration and linting

Makefile.am, src/http.c, src/main.c, src/userinput.c, src/userinput.h
This is a rework of the work from PR27, I've amended the issues raised during the code review. Also rebased on new master.
=> Implement two-factor authentication support

src/http.c
Extract key/value pairs from "key1=value1&key2=value2" strings more cleanly, using strtok(3) from the standard library.
Also use `const char *` instead of `char *` for not modified arguments.
=> http: Improve get_value_from_response using strtok

src/http.c
Username, password and realm are sent to the gateway using the HTTP
query string. Hence, they need to be properly escaped using
URL-encoding.
Fixes: #35
=> http: URL-encode values sent in requests

README.md, src/config.c, src/config.h
Just wanted to add these to config so I didn't have to type in --no-dns every time I started the tunnel.
Regards,
Kevin
=> add set-dns and set-routes flag to config file

src/http.c
=> http: Fix buffer overflow in parse_config

doc/openfortivpn.1.in, src/config.c, src/config.h, src/log.c, src/log.h, src/main.c
I've rebased this to latest head, see issue  #80 for details.
=> Add use-syslog command-line and config-file option

README.md, src/hdlc.h, src/io.c, src/ipv4.c, src/ipv4.h, src/log.c, src/ssl.h, src/tunnel.c, src/tunnel.h
I have rebased and squashed the mac os x port. 
The following commits are were merged into this one:
Added macOS build instructions to the readme (fretn)
more macOS stuff (fretn)
macOS documentation (fretn)
readme layout (fretn)
fix routing for 2 vpns under OS X (Michele Cella)
comply with coding style (mrbaseman)
correct indentation of enums with latest astyle (mrbaseman)
=> mac os x port

src/config.h, src/http.c, src/main.c
=> Add token-based one-time-password support

.gitignore, README.md, src/config.h, src/main.c
It has build error in Mac OSX Sierra with HomeBrew
It also has build error in Linux with clang (of cource).
=> Fix build error with clang

src/ipv4.c, src/ipv4.h
Fix to remain route to vpn server when disconnect if route to vpn server is already exist before connect.
And merge duplicated logic for adding route to vpn server.
=> Fix to remain exist route & merge duplicated logic

src/ipv4.c
Closes adrienverge/openfortivpn#114.
=> Fix buffer overrun

doc/openfortivpn.1.in, src/config.c, src/config.h, src/main.c, src/tunnel.c
=> implement ipparam to be passed to pppd

README.md
- fix indent
- modify dependencies
- add some decoration
=> modify README.md (modify dependencies, etc)

doc/openfortivpn.1.in, src/config.c, src/config.h, src/main.c
Hi,
I've had most of these commits laying around for a while; some could be a bit messy so feel free to be picky. I'm not 100% happy with the last one in particular myself :)
Comments/rework requests welcome
=> Routes improvements (maybe)

src/ipv4.c, src/ipv4.h, src/tunnel.c
=> dynamic allocation of memory for split route array

src/http.c
=> 2factor -> Two-factor

src/tunnel.c
Fix #175
Add missing new line and improve message.
=> Fix log message

README.md
=> Update Linux installation instructions

.travis.yml
As described here:
https://scan.coverity.com/travis_ci
=> Coverity automated scans on branch "coverity_scan"

src/http.c, src/ipv4.c, src/ssl.h
The scope of variables can be reduced.
=> Fix Codacy code style issues

src/tunnel.c
If /usr/sbin/pppd does not exist, print a specific message. When users
build from source, it happens often enough that PPP is not installed.
The existing frprintf(stderr, ...) call just after execvp() currently
doesn't work, probably because of the prior forkpty() call. If we get
it to work someday, we can move this after the failed call to execvp().
On the other hand a very specific message in case /usr/sbin/pppd is
missing makes sense, as this occurs quite often.
Because of limitations of C const-correctness, the execpv signature is:
char *const argv[]
but execvp() really doesn't change its arguments. Therefore it is valid
to pass an array of:
const char *const
then cast the array back to:
char *const *
just before calling execvp().
=> Does /usr/sbin/pppd exist?

src/config.c, src/config.h, src/http.c, src/io.c, src/ipv4.c, src/log.c, src/log.h, src/main.c, src/tunnel.c, src/userinput.c, src/xml.h
Use checkpatch.pl to identify and fix a few issues.
For now I'm leaving lots of issues as is because I feel
it would modify existing code way too much without clear
benefit.
=> Linux kernel coding style

configure.ac, doc/openfortivpn.1.in, src/tunnel.c
this branch implements the support proxy as requested in #150
=> Proxy support

src/config.h, src/ipv4.c, src/ipv4.h, src/main.c
=> struct initialization

src/config.c, src/config.h, src/hdlc.h, src/http.c, src/io.c, src/io.h, src/ipv4.c, src/ipv4.h, src/log.c, src/log.h, src/main.c, src/ssl.h, src/tunnel.c, src/tunnel.h, src/xml.c, src/xml.h
=> Normalize header inclusion

README.md, autogen.sh, configure.ac
this branch is to implement the improvements to the autoconf system as discussed in #222 
It is not yet ready to be merged, but in order to see how travis reacts on those changes I make it a pull request already
=> Improve autoconf

autogen.sh
* Standard stdout/stderr redirection.
* The last message is informational, not an error. Use sdtout, not stderr.
=> Bourne shell

src/ipv4.c, src/tunnel.c
...to `#ifdef __APPLE__ ... #else ... #endif`
combined with appropriate code reordering, where appropriate. this addresses #253
=> change #ifndef __APPLE__ ... #else ... #endif

src/main.c
Fixes #256 introduced by a926b34.
=> UINT_MAX is defined in <limits.h>

src/tunnel.c
Update comment to match the modified code.
=> Explain why Coverity defect is a false positive

doc/openfortivpn.1.in, src/main.c
=> Rephrase --half-internet-routes documentation

tests/ci/install_astyle.sh, tests/ci/install_openssl.sh
=> bash -> sh

src/tunnel.c
Prepare for addressing a Coverity warning.
=> Simplify ofv_append_varr()

README.md
Submitted to MacPorts https://trac.macports.org/ticket/56121
=> Update readme for install with MacPorts

README.md
In the main distribution for bionic and later, earlier with a ppa
=> Added Ubuntu packages

src/userinput.c
http://pubs.opengroup.org/onlinepubs/009695399/functions/fflush.html#tag_03_160_06
Fixes #360
=> Use fflush() after printf() as suggested by POSIX

src/ipv4.c
=> print ns2 instead

CHANGELOG.md, README.md, configure.ac
the description is restricted to the latest changes on the current master
since 1.7.1
* this addresses #338 at least for the upcoming release
* an update of the CHANGELOG.md file is needed if other PRs are landed earlier than this one
=> add CHANGELOG.md

src/main.c
I use the NetworkManager plugin and since errors are hidden in syslog, it took me a while to find out what went wrong when I just entered the gateway name without any port information into the config UI. At least according to the documentation I got will the default FortiClient also use port 443 if you don't enter anything special so this patch will make it use that port as well.
=> Use default HTTPS port 443 if none is specified

README.md
...and mention runtime dependency ppp or pppd
=> update README.md: add dependency "make" for Fedora (server)

configure.ac, src/config.c, src/ipv4.c, src/tunnel.c
=> use strtoul to correctly convert to unsigned long

src/tunnel.c
this might be helpful for #428
=> increase speed setting for pppd

src/http.c
Part 2 with encoding. This works too for me.
=> fix (http request): pass single space with encoding

doc/openfortivpn.1.in, src/config.c, src/http.c, src/io.c, src/ipv4.c, src/ipv4.h, src/main.c, src/ssl.h, src/tunnel.c, src/tunnel.h, src/xml.c
Run aspell.
Capitalization for acronyms.
=> Spelling and readability

src/tunnel.c
Prepare code for documenting Coverity issues.
=> Readability

src/http.c, src/main.c
...and try to solve login problems with certificate only (#375)
=> fix for #496

README.md
The package has been moved from the AUR to the community repository
=> Fixed Arch Linux package link

README.md
they have changed their package management infrastructure
=> update link for Solus in README.md

Makefile.am, configure.ac, doc/openfortivpn.1.in, src/ipv4.c, src/main.c
this implements the feature request from #486 and #101
=> use resolvconf if available to update resolv.conf

src/tunnel.c
=> Fix indentation style issue in tunnel.c

src/config.c, src/http.c, src/io.c, src/ipv4.c, src/log.c, src/main.c, src/ssl.h, src/tunnel.c, src/userinput.c, src/xml.c
mostly white space issues where checkpatch is stricter than our lint script
=> coding style fixes

Makefile.am
As discussed in https://github.com/Homebrew/homebrew-core/pull/50728.
=> Fixed Makefile compatibility with BSD sed

tests/lint/line_length.py
Add documentation to Python scripts
=> Fix Code Inspector issues

src/config.h, src/hdlc.h, src/http.h, src/io.h, src/ipv4.h, src/log.h, src/ssl.h, src/tunnel.h, src/userinput.h, src/xml.h
=> Compliant header guards

src/ipv4.c, src/tunnel.c
Use standard C function strchr() instead of deprecated POSIX function index().
=> index → strchr

src/config.c, src/http.c, src/ipv4.c, src/tunnel.c
Standardize on threadsafe strtok_r() throughout the source code.
=> strtok → strtok_r

src/tunnel.c
CID 355059:  Null pointer dereferences  (FORWARD_NULL)
Passing "&saveptr" to "__strtok_r_1c", which dereferences null "saveptr".
Perhaps I am missing something here, but this Coverity Scan message doesn't
make much sense as is. I suspect it complains about the possibility of both
the "str" and "saveptr" arguments of strtok_r() being NULL.
=> Fix Coverity defects

src/http.c
Seems a simplistic fix for issue #575 
"it works here" ;-)
=> Doubled BUFSZ to fix #575

configure.ac, doc/openfortivpn.1.in, src/config.c, src/config.h, src/ipv4.c, src/main.c
=> add configure and command line option for resolvconf

src/hdlc.c, src/hdlc.h, src/io.c, src/main.c
* Improves 32f1949.
* Fixes #560.
=> Initialize need_flag_sequence close to hdlc.c

configure.ac
=> improve help strings for resolvconf configure options

.travis.yml
=> Get Travis CI to build on macOS and FreeBSD

Makefile.am
* Make sure share/openfortivpn/config.template is world-readable.
* Do not comment first 2 lines.
=> Minor changes to config file

src/ipv4.c
we do this already on mac and bsd
=> do not use interface ip for routing on linux

src/io.c, src/ipv4.c, tests/lint/line_length.py
=> Better document buffer lengths

src/io.c
Enhancement to help around issue #540
=> check return values for threads in io.c

src/io.c
Segfault introduced by a171722.
=> Fix segfault

src/io.c, src/tunnel.c
warning: Potential leak of memory pointed to by 'pppd_args.data'
=> GCC 9 warnings

src/http.c
Return the response in a larger buffer instead of spending time shrinking the buffer.
Return ERR_HTTP_TOO_LONG instead of bailing out with assert() if overflow.
=> Avoid a realloc() call

doc/openfortivpn.1.in, src/main.c
=> Document options that apply to TLS v1.2 or lower

src/main.c
Use 0 in C++ (up to C++11) and NULL in C.
=> Initialize pointers with NULL

tests/ci/checkpatch/checkpatch.pl, tests/ci/checkpatch/spelling.txt, tests/lint/checkpatch.sh
The default max line length has been changed from 80 to 100. It's about time!
=> Update checkpatch.pl from Linux kernel

src/config.c, src/main.c
=> Always define the User agent

src/http.c
reported by coverity scan (CID 359894)
=> fix a  possible null pointer dereference

README.md
Stress this is a mere example and explain how to adapt it.
=> Make it clear this is an example

CHANGELOG.md, configure.ac
Version bump and changelog update. Fixes #779
=> Version bump to 1.15.0

src/tunnel.c
CID 182343: Resource leak (RESOURCE_LEAK)
leaked_handle: Handle variable handle going out of scope leaks the handle.
=> Fix Coverity defect

src/tunnel.c
* clean up PPP exit status code reporting
* propagate PPP exit status code to main()
Fixes #797.
=> PPP exit status code

.github/workflows/coverity-scan.yml
Inspired by:
https://github.com/ruby/actions-coverity-scan
Replay #855.
=> Support Coverity Scan from GitHub Actions

.github/workflows/openfortivpn.yml
There are more benefits than drawbacks to checking both pull requests and direct pushes to the `master` branch.
=> Revert 68ddf5c

README.md
Add repology badges to display the packaging status in all known repositories. It's nice to compare versions and provides easy browseable access to each repository.
=> Add repology link

src/http.c, src/userinput.c
=> atoi → strtol

src/userinput.c
=> Fix buffer overflow in URI escaping function

src/http.c, src/main.c
=> Different hint for each different connection

src/config.c, src/main.c
Fixes #896 and a couple minor memory leaks at exit.
=> Memory management issues

src/tunnel.c
The following resources seem to  always be allocated in this order:
```
ssl_socket
ssl_context
ssl_handle
```
Release them in the reverse order:
```
ssl_handle
ssl_context
ssl_socket
```
Hopefully helps to fix #462.
=> Release allocated SSL resources

CHANGELOG.md, README.md, configure.ac
=> openfortivpn version 1.17.0

CHANGELOG.md, configure.ac
=> openfortivpn version 1.17.1

.github/workflows/codeql-analysis.yml, src/config.c, src/ipv4.c, src/main.c
See https://github.com/github/codeql/issues/6504#issuecomment-901147947.
=> Have CodeQL run LGTM.com tests

src/config.c, src/main.c
Use these range values for readability.
=> Valid ports are in the 1-65535 range

src/config.c
* Release resources in reverse resource allocation order.
* Restore `errno` to value at initial error location before returning.
=> Improve error handling in #952

CHANGELOG.md, configure.ac
=> openfortivpn version 1.17.3

README.md
=> doc: update Fedora/CentOS link in README.md

CHANGELOG.md, configure.ac
=> openfortivpn version 1.18.0

.github/workflows/codeql-analysis.yml, .github/workflows/codespell.yml, .github/workflows/coverity-scan.yml, .github/workflows/openfortivpn.yml
https://github.com/actions/checkout
=> Update GitHub Actions

CHANGELOG.md, configure.ac
=> openfortivpn version 1.19.0

.github/workflows/openfortivpn.yml, tests/lint/run.sh
=> Update OpenSSL minimal version: 0.9.8 → 1.0.2

.github/workflows/codeql-analysis.yml
Use the latest template workflow from:
https://github.com/github/codeql-action#usage
=> Update CodeQL Action

src/main.c
=> Fix recent bugs

CHANGELOG.md
=> openfortivpn version 1.20.0

CHANGELOG.md, configure.ac
Fixes #1090.
Contains a fix for #1088.
=> openfortivpn version 1.20.2

lib/systemd/system/openfortivpn@.service.in
Based on equivalent OpenVPN file:
`distro/systemd/openvpn-server@.service.in`
See also OpenVPN service:
https://community.openvpn.net/openvpn/wiki/Systemd
=> Improve openfortivpn@.service

CHANGELOG.md, configure.ac
=> openfortivpn version 1.20.3

CHANGELOG.md, configure.ac
=> openfortivpn version 1.20.4

README.md
=> Fix link to Arch Linux package

CHANGELOG.md, configure.ac
=> openfortivpn 1.21.0

.github/workflows/codeql-analysis.yml
https://github.com/github/codeql-action
=> Bump github/codeql-action

src/config.c, src/hdlc.c, src/http.c, src/io.c, src/log.c, src/tunnel.c, src/xml.c
Apply to loop variables so that they don't leak out of the loop - unless they leak on purpose.
=> Use C99 like the Linux kernel

src/ipv4.c, src/ssl.h
Apply to loop variables so that they don't leak out of the loop - unless they leak on purpose.
=> Use C99 like the Linux kernel, again

lib/systemd/system/openfortivpn@.service.in
From https://github.com/adrienverge/openfortivpn/issues/93#issuecomment-1925866991
=> Improve systemd unit file

CHANGELOG.md, configure.ac
Fixes #1210, and possibly #1208.
=> openfortivpn 1.22.0

CHANGELOG.md, configure.ac
Fixes #1214.
Supersedes #1215.
=> openfortivpn 1.22.1

README.md
I've added newest package to alpine test repository: https://pkgs.alpinelinux.org/package/edge/testing/x86_64/openfortivpn and updated README.md
=> Add Alpine Linux package to README.md

src/ipv4.c
Use `size_t` and `ssize_t` for file and memory access. No need to specify a fixed size in this case.
Add assertions to silence Coverity Scan warnings. These are not actual issues, the size of system config files is limited in real life.
=> Avoid irrelevant fixed-size type uint32_t
